services:
  db:
   image: mysql:latest
   container_name: mysql-db
   restart: always
   ports:
     - 3306:3306
   environment:
      - MYSQL_ROOT_PASSWORD=secret
   volumes:
      - "../converter.sql:/docker-entrypoint-initdb.d/converter.sql"
